language: go

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - docker build . -t pnyak/api-test:latest
  - docker build . -t pnyak/api-test:${TRAVIS_BUILD_ID}.${TRAVIS_BUILD_NUMBER}

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pnyak/api-test:latest
  - docker push pnyak/api-test:${TRAVIS_BUILD_ID}.${TRAVIS_BUILD_NUMBER}
